// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./../layout/Aside.vue')['default']
    BreadCrumb: typeof import('./../components/BreadCrumb/src/BreadCrumb.vue')['default']
    Dialog: typeof import('./../components/Dialog/src/Dialog.vue')['default']
    DialogAlert: typeof import('./../components/DialogAlert/src/DialogAlert.vue')['default']
    DisplayDocx: typeof import('./../components/DisplayDocx/src/DisplayDocx.vue')['default']
    Drawer: typeof import('./../components/Drawer/src/Drawer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header: typeof import('./../layout/Header.vue')['default']
    Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
    JsonEditor: typeof import('./../components/JsonEditor/src/JsonEditor.vue')['default']
    Layout: typeof import('./../layout/Layout.vue')['default']
    Pagination: typeof import('./../components/Pagination/src/Pagination.vue')['default']
    Progress: typeof import('./../components/Progress/src/Progress.vue')['default']
    Quill: typeof import('./../components/Quill/src/Quill.vue')['default']
    Resize: typeof import('./../components/Resize/src/Resize.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Search/src/Search.vue')['default']
    SearchItem: typeof import('./../components/Search/src/SearchItem.vue')['default']
    Table: typeof import('./../components/Table/src/Table.vue')['default']
    TableOld: typeof import('./../components/Table/src/TableOld.vue')['default']
    TableSearch: typeof import('./../components/TableSearch/src/TableSearch.vue')['default']
    Title: typeof import('./../components/Title/src/Title.vue')['default']
    Tooltip: typeof import('./../components/Tooltip/src/Tooltip.vue')['default']
    VideoPlay: typeof import('./../components/VideoPlay/src/VideoPlay.vue')['default']
    WangEditor: typeof import('./../components/WangEditor/src/WangEditor.vue')['default']
  }
}
