// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./../layout/Aside.vue')['default']
    BreadCrumb: typeof import('./../components/BreadCrumb/src/BreadCrumb.vue')['default']
    Cell: typeof import('./../components/Cell.vue')['default']
    Dialog: typeof import('./../components/Dialog/src/Dialog.vue')['default']
    DialogAlert: typeof import('./../components/DialogAlert/src/DialogAlert.vue')['default']
    DisplayDocx: typeof import('./../components/DisplayDocx/src/DisplayDocx.vue')['default']
    DocxPreview: typeof import('./../components/DisplayDocx/src/DocxPreview.vue')['default']
    Drawer: typeof import('../components/Drawer/src/Drawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./../layout/Header.vue')['default']
    Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
    Layout: typeof import('./../layout/Layout.vue')['default']
    Pagination: typeof import('./../components/Pagination/src/Pagination.vue')['default']
    Preview: typeof import('./../components/Preview.vue')['default']
    Progress: typeof import('./../components/Progress/src/Progress.vue')['default']
    Resize: typeof import('./../components/Resize/src/Resize.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Search/src/Search.vue')['default']
    SearchItem: typeof import('./../components/Search/src/SearchItem.vue')['default']
    Table: typeof import('./../components/Table/src/Table.vue')['default']
    TableOld: typeof import('./../components/Table/src/TableOld.vue')['default']
    TableSearch: typeof import('./../components/TableSearch/src/TableSearch.vue')['default']
    Title: typeof import('./../components/Title/src/Title.vue')['default']
    Tooltip: typeof import('./../components/Tooltip/src/Tooltip.vue')['default']
    VideoPlay: typeof import('./../components/VideoPlay/src/VideoPlay.vue')['default']
  }
}
